# Generated by Django 5.0.2 on 2024-02-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('passed', models.BooleanField()),
            ],
        ),
    ]
