# Generated by Django 5.0.2 on 2024-02-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
