# Generated by Django 5.0.2 on 2024-02-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_passed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='roll_no',
        ),
    ]
