# Generated by Django 5.0.2 on 2024-02-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_id_student_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='id',
        ),
    ]
